// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfFZh77wuuhSBydtrqz6dyJZgPp4GMviM',
    appId: '1:727734347697:web:7a7076f4eb5b36fec43f90',
    messagingSenderId: '727734347697',
    projectId: 'studio-next-light',
    authDomain: 'studio-next-light.firebaseapp.com',
    storageBucket: 'studio-next-light.appspot.com',
    measurementId: 'G-F7QD9R5GD2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2kHM3_X0ONDGMTkWBqdlp_WpWksUpxyo',
    appId: '1:727734347697:android:68d268f37a0b5c14c43f90',
    messagingSenderId: '727734347697',
    projectId: 'studio-next-light',
    storageBucket: 'studio-next-light.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtzeWOl_v8bYxLAmBgxu5hlM14AN1Cl6U',
    appId: '1:727734347697:ios:98d06cf6a0039b6dc43f90',
    messagingSenderId: '727734347697',
    projectId: 'studio-next-light',
    storageBucket: 'studio-next-light.appspot.com',
    iosBundleId: 'com.heavenonthisearth.studioNextLight',
  );
}
